<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="vi"><head><title>Thư viện video</title></head><body>
<span class="eyebrow">HỌC MỖI NGÀY</span><h1>${adminShop ? 'Quản lý nguồn video' : 'Thư viện bài giảng'}</h1>
<c:if test="${not empty message}"><p class="success" role="status"><c:out value="${message}"/></p></c:if><c:if test="${not empty error}"><p class="error" role="alert"><c:out value="${error}"/></p></c:if>
<form method="get" class="searchbar"><label for="q">Tìm bài giảng / danh mục</label><input id="q" name="q" maxlength="100" value="<c:out value='${param.q}'/>" placeholder="Java, Servlet, SQL…"><button>Tìm kiếm</button></form>
<c:if test="${adminShop}"><p class="muted">Gắn file có sẵn trong /videos hoặc URL HTTPS của MP4/WebM. Để trống và lưu để gỡ nguồn. Video mẫu được lưu nội bộ và không cần Internet.</p></c:if>
<c:if test="${empty lessons}"><p class="empty-state">Không tìm thấy bài giảng phù hợp.</p></c:if>
<div class="video-grid"><c:forEach var="v" items="${lessons}"><article class="video-card"><c:url var="detail" value="/video"><c:param name="id" value="${v.VideoId}"/></c:url><c:url var="poster" value="${empty v.Poster ? '/assets/images/poster.svg' : v.Poster}"/>
<a href="<c:out value='${detail}'/>"><img src="<c:out value='${poster}'/>" loading="lazy" alt="Bài giảng"></a><div class="video-info"><p class="eyebrow"><c:out value="${v.Categoryname}"/></p><h2><a href="<c:out value='${detail}'/>"><c:out value="${v.Title}"/></a></h2><p class="badge">${empty v.MediaUrl ? 'Chưa có nguồn phát' : '▶ Có video để xem'}</p>
<c:if test="${adminShop}"><p>Mã video: <c:out value="${v.VideoId}"/></p><form method="post"><input type="hidden" name="csrf" value="${csrf}"><input type="hidden" name="videoId" value="<c:out value='${v.VideoId}'/>"><label>Nguồn MP4/WebM<input name="mediaUrl" maxlength="1000" value="<c:out value='${v.MediaUrl}'/>" placeholder="/videos/java-01.mp4"></label><button>Lưu nguồn video</button></form></c:if></div></article></c:forEach></div>
<nav class="pagination"><c:if test="${libraryPage > 1}"><c:url var="previous" value="${adminShop ? '/admin/media' : '/library'}"><c:param name="q" value="${param.q}"/><c:param name="page" value="${libraryPage-1}"/></c:url><a href="<c:out value='${previous}'/>">← Trước</a></c:if><span>Trang ${libraryPage}</span><c:if test="${lessons.size() == 12}"><c:url var="next" value="${adminShop ? '/admin/media' : '/library'}"><c:param name="q" value="${param.q}"/><c:param name="page" value="${libraryPage+1}"/></c:url><a href="<c:out value='${next}'/>">Sau →</a></c:if></nav>
</body></html>
